version: "3.9"

services:
  api:
    build:
      context: ./api/
    container_name: api
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend/
    container_name: frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
